@base_url = https://blockstuff-api.safatanc.com
@access_token = AccessTokenHere

### Login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "username": "Agilistikmal",
  "password": "Rahasia123"
}

### Register
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "username": "agilistikmal",
  "email": "agilistikmal3@gmail.com",
  "phone": "+6281346173829",
  "full_name": "Agil Ghani Istikmal",
  "password": "Rahasia123"
}

### Verify
POST {{base_url}}/auth/verify
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjIyMjE2NjAsInVzZXIiOnsiaWQiOiI5ZjllOWRiNy0wODgxLTQ0MzktOTYyZi01NWExZTU2ZjExZGUiLCJ1c2VybmFtZSI6ImFnaWxpc3Rpa21hbCIsImVtYWlsIjoiYWdpbGlzdGlrbWFsM0BnbWFpbC5jb20iLCJwaG9uZSI6Iis2MjgxMzQ2MTczODI5IiwiZnVsbF9uYW1lIjoiQWdpbCBHaGFuaSBJc3Rpa21hbCIsInJvbGUiOiJBRE1JTiIsImNyZWF0ZWRfYXQiOiIyMDI0LTA3LTI0VDA3OjQxOjIyLjczNjA3OSswNzowMCIsInVwZGF0ZWRfYXQiOiIyMDI0LTA3LTI0VDA3OjQxOjIyLjczNjA3OSswNzowMCJ9fQ.SLZ0OS5X4vru-MdreQOP6eo__rbr1blb_Fjft4gWWNk"
}