@base_url = https://blockstuff-api.safatanc.com
@access_token = AccessTokenHere

### Login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "username": "agilistikmal",
  "password": "Rahasia123"
}

### Register
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "username": "agilistikmal",
  "email": "agilistikmal3@gmail.com",
  "phone": "+6281346173829",
  "full_name": "Agil Ghani Istikmal",
  "password": "Rahasia123"
}