@base_url = http://localhost:5000
@access_token = AccessTokenHere

### Login
POST {{base_url}}/auth/login
Content-Type: application/json

{
  "username": "ghani",
  "password": "Rahasia123"
}

### Register
POST {{base_url}}/auth/register
Content-Type: application/json

{
  "username": "ghani",
  "email": "ghani3@gmail.com",
  "phone": "+6281346173829",
  "full_name": "Ghani Al Ghani",
  "password": "Rahasia123"
}