@base_url = http://localhost:8001
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE4NjgwODcsInVzZXJuYW1lIjoiYWdpbGlzdGlrbWFsIn0.FMGQC8swsYpg79wTi-wiHk_TiBEAVeDLNQHbCkPF5Uk

### Find All Minecraft Servers
GET {{base_url}}/minecraftserver

### Find Minecraft Server by IP
GET {{base_url}}/minecraftserver/play.ghani.net

### Find Minecraft Server by IP with details
GET {{base_url}}/minecraftserver/play.ghani.net/detail
Authorization: Bearer {{access_token}}

### Create Minecraft Server
POST {{base_url}}/minecraftserver
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "ip": "play.ghani.net",
  "slug": "ghani-mc",
  "name": "Ghani Minecraft",
  "author_id": "9f9e9db7-0881-4439-962f-55a1e56f11de"
}

### Update Minecraft Server
PATCH {{base_url}}/minecraftserver/77af08ee-7f83-4d40-8fde-bb50ae1801f0
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "GhaniCraft"
}

### Update Minecraft Server Rcon
PATCH {{base_url}}/minecraftserver/77af08ee-7f83-4d40-8fde-bb50ae1801f0/rcon
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "ip": "rcon.ghani.net",
  "port": 1234,
  "password": "RconPassword@123"
}

### Delete Minecraft Server
DELETE {{base_url}}/minecraftserver/c014dadc-6c58-43f2-9cb7-5646c069e41a
Authorization: Bearer {{access_token}}