@base_url = http://localhost:5000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE4NzM1NzksInVzZXJuYW1lIjoiYWdpbGlzdGlrbWFsIn0.A4DC_wOP_REbAfXRVIm4LaD481KNysTr2h8HAg3am2g

### Find All Payouts
GET {{base_url}}/payout
Authorization: Bearer {{access_token}}

### Find All Payouts Waiting Approval
GET {{base_url}}/payout?status=WAITING_APPROVAL
Authorization: Bearer {{access_token}}

### Find All Payouts Approved
GET {{base_url}}/payout?status=APPROVED
Authorization: Bearer {{access_token}}

### Find Payout by ID
GET {{base_url}}/payout/72406b24-4e33-4fc6-9e9a-cf63f8709ff3
Authorization: Bearer {{access_token}}

### Create Payout Request
POST {{base_url}}/payout
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "payout_transactions": [
    {
      "transaction_id": "dda06193-7030-4b91-bd58-373734c39153"
    }
  ]
}

### Update Payout
PATCH {{base_url}}/payout/72406b24-4e33-4fc6-9e9a-cf63f8709ff3
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "status": "APPROVED"
}

### Delete by ID
DELETE {{base_url}}/payout/88a5379a-4c9a-4ab0-9569-391cb69a0c2f
Authorization: Bearer {{access_token}}