@base_url = http://localhost:5000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE2OTk4MDYsInVzZXJuYW1lIjoiYWdpbGlzdGlrbWFsIn0.NgEjAsdsA0YBb6l2jeADmkSkkSLyrmVyrPcubzlWpwE

### Find All Minecraft Server Items
GET {{base_url}}/transaction
Authorization: Bearer {{access_token}}

### Find Item by Slug
GET {{base_url}}/transaction/BS-AsdbS617

### Create Transaction
POST {{base_url}}/transaction
Content-Type: application/json
  
{
  "minecraft_username": "agilistikmal",
  "email": "agilistikmal3@gmail.com",
  "transaction_items": [
    {
      "item_id": "2bf8a0c3-c960-4c6d-90be-63b79d226f80"
    }
  ]
}

### Update
PATCH {{base_url}}/transaction/f1ca1f6a-94d9-4539-b710-03c2f782f4c9
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "status": "PAID"
}

### Delete by ID
DELETE  {{base_url}}/transaction/230c9b19-e29c-4578-9580-d8e2bcb59b47
Authorization: Bearer {{access_token}}