@base_url = http://localhost:5000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE4NjU2OTUsInVzZXJuYW1lIjoiYWdpbGlzdGlrbWFsIn0.y9oDrcECywMzokf9PcUjGUdPo_ydawQYguAGi7MED48

### Find All Transactions
GET {{base_url}}/transaction
Authorization: Bearer {{access_token}}

### Find Transaction by Code
GET {{base_url}}/transaction/BS-npTxyxOgqV

### Create Transaction
POST {{base_url}}/transaction
Content-Type: application/json
  
{
  "minecraft_username": "agilistikmal",
  "email": "agilistikmal3@gmail.com",
  "transaction_items": [
    {
      "item_id": "2bf8a0c3-c960-4c6d-90be-63b79d226f80"
    }
  ]
}

### Update
PATCH {{base_url}}/transaction/48d0c43c-9840-4b7d-b69e-592d3eca53a1
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "status": "PAID"
}

### Delete by ID
DELETE  {{base_url}}/transaction/48d0c43c-9840-4b7d-b69e-592d3eca53a1
Authorization: Bearer {{access_token}}