@base_url = http://localhost:5000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjM1MTE2MzUsInVzZXIiOnsiaWQiOiI5ZjllOWRiNy0wODgxLTQ0MzktOTYyZi01NWExZTU2ZjExZGUiLCJ1c2VybmFtZSI6ImFnaWxpc3Rpa21hbCIsImVtYWlsIjoiYWdpbGlzdGlrbWFsM0BnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiZW1haWxfdmVyaWZ5X2NvZGUiOiJUR1hOcyIsInBob25lIjoiKzYyODEzNDYxNzM4MjkiLCJmdWxsX25hbWUiOiJBZ2lsIEdoYW5pIElzdGlrbWFsIiwicm9sZSI6IkFETUlOIiwiY3JlYXRlZF9hdCI6IjIwMjQtMDctMjRUMDc6NDE6MjIuNzM2MDc5KzA3OjAwIiwidXBkYXRlZF9hdCI6IjIwMjQtMDgtMDhUMDk6MDQ6MDMuNTU0NjIyKzA3OjAwIn0sInVzZXJuYW1lIjoiYWdpbGlzdGlrbWFsIn0.vIZO8mWn5tLaCphnyRhC7gav4Mtekq_pv_65xRU9JJw

### Find All Users
GET {{base_url}}/user
Authorization: Bearer {{access_token}}

### Find User by Username
GET {{base_url}}/user/agilistikmal
Authorization: Bearer {{access_token}}

### Find User by ID
GET {{base_url}}/user/id/9f9e9db7-0881-4439-962f-55a1e56f11de
Authorization: Bearer {{access_token}}

### Create User
POST {{base_url}}/user
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "username": "ghani",
  "email": "ghani3@gmail.com",
  "phone": "+6281346173829",
  "full_name": "Ghani Al Ghani",
  "password": "Rahasia123"
}

### Update User
PATCH {{base_url}}/user/3cc09e1f-2356-4a8d-ac8b-1dd63c3e5601
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "role": "ADMIN"
}

### Delete User
DELETE {{base_url}}/user/e5181182-5db1-4a9f-8dc0-ae25cd90b2aa
Authorization: Bearer {{access_token}}
