@base_url = http://localhost:5000
@access_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MjE3OTE3MTQsInVzZXJuYW1lIjoiZ2hhbmkifQ.1QFjZFEptyho5Todd5x3rzfJ5p7wOGxzprliYTqgJE4

### Find All Users
GET {{base_url}}/user
Authorization: Bearer {{access_token}}

### Find User by Username
GET {{base_url}}/user/ghani
Authorization: Bearer {{access_token}}

### Create User
POST {{base_url}}/user
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "username": "ghani",
  "email": "ghani3@gmail.com",
  "phone": "+6281346173829",
  "full_name": "Ghani Al Ghani",
  "password": "Rahasia123"
}

### Update User
PATCH {{base_url}}/user/3cc09e1f-2356-4a8d-ac8b-1dd63c3e5601
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "role": "ADMIN"
}

### Delete User
DELETE {{base_url}}/user/e5181182-5db1-4a9f-8dc0-ae25cd90b2aa
Authorization: Bearer {{access_token}}